
version: 2

models:
  - name: bq_marge
    description: "A dbtmodel to marge into bq table"
    columns:
      - name: PassengerId
        description: "The primary key for this table"
        data_tests:
          - unique
          - not_null
