name: taxitrip-data

profile: taxitrip-data

seed-paths: ["seeds"]
model-paths: ["models"]
macro-paths: ["macros"]
test-paths: ['tests']

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"

seeds:
  # Builds seeds into '<your_schema_name>_raw'
  taxitrip-data:
    +schema: raw

models:
  taxitrip-data:
    # Materialize staging models as views, and marts as tables
    staging:
      +materialized: view
    source:
      +materialized: table
    mart:
      +materialized: table
